version: "3"
services:
  postgres:
    image: "postgres:16.0"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  db_data:
    driver: local
